<a href="https://colab.research.google.com/github/hazemovic17/Loan-Default-Risk-Analysis/blob/main/Loan_default_risk_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Buisness** **Understanding**

In [2]:
# Loan Default Risk Analysis

## Business Problem

#Financial institutions face significant financial losses due to customer loan defaults.

#The objective of this project is to analyze customer characteristics, identify factors contributing to loan default, segment customers based on risk, and provide data-driven recommendations that support lending decisions.

---

## Objectives

-# Understand customer behavior
-# Identify factors affecting default
-# Analyze portfolio risk: This involves evaluating the overall risk exposure of the loan portfolio, considering factors like concentration risk, credit risk, and market risk. It assesses the potential for losses across the entire collection of loans and understands how different risks interact.
-# Build customer risk segments
-# Generate business recommendations

SyntaxError: invalid syntax (3439071979.py, line 5)

**Import Libraries**

In [3]:
import pandas as pd #3shan nload el csv file
import numpy as np #3shan el complex math

import matplotlib.pyplot as plt #3shan elvisuals
import seaborn as sns #3shan visuals a7sb bs visuals mn loghet R

import warnings #3shan yskip ay warning fyh ignore
warnings.filterwarnings("ignore")

plt.style.use("ggplot")

**Load Dataset**

In [5]:
df = pd.read_csv("Loan_default.csv")

In [6]:
df.head(10)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
5,A9S62RQ7US,25,90298,90448,720,18,2,22.72,24,0.10,High School,Unemployed,Single,Yes,No,Business,Yes,1
6,H8GXPAOS71,38,111188,177025,429,80,1,19.11,12,0.16,Bachelor's,Unemployed,Single,Yes,No,Home,Yes,0
7,0HGZQKJ36W,56,126802,155511,531,67,4,8.15,60,0.43,PhD,Full-time,Married,No,No,Home,Yes,0
8,1R0N3LGNRJ,36,42053,92357,827,83,1,23.94,48,0.20,Bachelor's,Self-employed,Divorced,Yes,No,Education,No,1
9,CM9L1GTT2P,40,132784,228510,480,114,4,9.09,48,0.33,High School,Self-employed,Married,Yes,No,Other,Yes,0

In [7]:
df.shape # (x,y)=(rows,columns)

(255347, 18)

In [8]:
df.info() # esm kol column, eltype bta3o ,3add elrows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB

**Data Profiling**

In [9]:
df.describe().T # T for transpose

,count,mean,std,min,25%,50%,75%,max
Age,255347.0,43.498306,14.990258,18.0,31.00,43.00,56.00,69.0
Income,255347.0,82499.304597,38963.013729,15000.0,48825.50,82466.00,116219.00,149999.0
LoanAmount,255347.0,127578.865512,70840.706142,5000.0,66156.00,127556.00,188985.00,249999.0
CreditScore,255347.0,574.264346,158.903867,300.0,437.00,574.00,712.00,849.0
MonthsEmployed,255347.0,59.541976,34.643376,0.0,30.00,60.00,90.00,119.0
NumCreditLines,255347.0,2.501036,1.117018,1.0,2.00,2.00,3.00,4.0
InterestRate,255347.0,13.492773,6.636443,2.0,7.77,13.46,19.25,25.0
LoanTerm,255347.0,36.025894,16.969330,12.0,24.00,36.00,48.00,60.0
DTIRatio,255347.0,0.500212,0.230917,0.1,0.30,0.50,0.70,0.9
Default,255347.0,0.116128,0.320379,0.0,0.00,0.00,0.00,1.0

In [10]:
# Select only numerical columns
num_cols = df.select_dtypes(include='number')
# num_cols dA variable shayl kol table el loan wa (select_dtypes) bt7dad no3 mo3yn mn elcolumns ya get included fy num columns zy hena numbers bs


# Create profiling summary
profiling = pd.DataFrame({
    "Count": num_cols.count(),
    "Missing Values": num_cols.isnull().sum(),
    "Mean": num_cols.mean(),
    "Median (Q2)": num_cols.median(),
    "Min": num_cols.min(),
    "Q1": num_cols.quantile(0.25),
    "Q3": num_cols.quantile(0.75),
    "Max": num_cols.max()
})

# Calculate IQR
profiling["IQR"] = profiling["Q3"] - profiling["Q1"]

# Calculate Outlier Limits
profiling["Lower Limit"] = profiling["Q1"] - 1.5 * profiling["IQR"]
profiling["Upper Limit"] = profiling["Q3"] + 1.5 * profiling["IQR"]

# tb3n kol da 3shan acheck fy outliers wla la 3shan bashof fy haga msln  ta7t el loweer limit wla la
# Round numbers
profiling = profiling.round(2)

profiling

,Count,Missing Values,Mean,Median (Q2),Min,Q1,Q3,Max,IQR,Lower Limit,Upper Limit
Age,255347,0,43.50,43.00,18.0,31.00,56.00,69.0,25.00,-6.50,93.50
Income,255347,0,82499.30,82466.00,15000.0,48825.50,116219.00,149999.0,67393.50,-52264.75,217309.25
LoanAmount,255347,0,127578.87,127556.00,5000.0,66156.00,188985.00,249999.0,122829.00,-118087.50,373228.50
CreditScore,255347,0,574.26,574.00,300.0,437.00,712.00,849.0,275.00,24.50,1124.50
MonthsEmployed,255347,0,59.54,60.00,0.0,30.00,90.00,119.0,60.00,-60.00,180.00
NumCreditLines,255347,0,2.50,2.00,1.0,2.00,3.00,4.0,1.00,0.50,4.50
InterestRate,255347,0,13.49,13.46,2.0,7.77,19.25,25.0,11.48,-9.45,36.47
LoanTerm,255347,0,36.03,36.00,12.0,24.00,48.00,60.0,24.00,-12.00,84.00
DTIRatio,255347,0,0.50,0.50,0.1,0.30,0.70,0.9,0.40,-0.30,1.30
Default,255347,0,0.12,0.00,0.0,0.00,0.00,1.0,0.00,0.00,0.00

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['LoanID'].nunique() # to check primary key uniqueness

255347

In [14]:
df.dtypes

LoanID             object
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education          object
EmploymentType     object
MaritalStatus      object
HasMortgage        object
HasDependents      object
LoanPurpose        object
HasCoSigner        object
Default             int64
dtype: object